"""P2-10/P2-12/P2-11 user columns: monthly free credits, token expiry, password reset

Revision ID: 733d2d970515
Revises: 171777e71dff
Create Date: 2026-07-11 04:41:11.269814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733d2d970515'
down_revision = '171777e71dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_month', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('token_issued_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_token_issued_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_column('reset_token_issued_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('token_issued_at')
        batch_op.drop_column('credits_month')

    # ### end Alembic commands ###
